Fix call to httpie
Error: "The program 'http' is currently not installed. To run 'http'
please ask your administrator to install the package 'httpie'."

Testing against the following PRs:

Required PR: https://github.com/pulp/pulp_file/pull/65
Required PR: https://github.com/PulpQE/pulp-smash/pull/770